USE [Base60_PROD2]
GO
/****** Object:  StoredProcedure [dbo].[ETL_TRANSACTION_INS]    Script Date: 9/3/2025 1:48:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO












ALTER PROCEDURE [dbo].[ETL_TRANSACTION_INS]
AS BEGIN


INSERT INTO AML_TRANSACTION (TXNID, TXNDATE, TXNREFNO, TXNTYPE, TXNSUBTYPE, TXNMODE, TXNAMOUNT, INOUT, BRANCHCODE, CURRENCY, EXCHANGERATE,REMARKS,
		PURPOSE, CPNAME1, IMPORTED_DATE, CPNAME2, CPNAME3, CPADDRESS1, CPADDRESS2, CPADDRESS3, CORRESPONDENTBANK, CORRESBANKCOUNTRYCODE,
		CORRESBANKADDRESS1, CORRESBANKADDRESS2, CORRESBANKADDRESS3, PRODUCTTYPE, INCEPTIONDATE, MATUITYDATE, TXNNATURE, FUNDSSOURCE, FXAMOUNT,
		SOURCE, INPUTDATE, DEBIT_CREDIT, BENEFICIARYNAME1, BENEFICIARYNAME2, BENEFICIARYNAME3, BENEFICIARY_ACCOUNTNO, BENEFICIARY_NAME_FLAG, 
		BENEFICIARYADDRESS1, BENEFICIARYADDRESS2, BENEFICIARYADDRESS3, ACCOUNTID, OPACCOUNTNO, SRCTXNTYPE, SRC_TXN_REFNO, cpaccountno, AccountNumber,
		STOCKREFNO, NOOFSHARES, NETASSETVALUE, REGION, TXN_DATE_TIME, RUNID, RUNDATE)



select 
(SELECT max(txnid) from AML_TRANSACTION) + ROW_NUMBER() OVER (ORDER BY A.TXNREFNO) AS TXNID,
CASE WHEN a.SOURCE = 'REM-DEPO' THEN a.TXNDATE ELSE TXN_DATE_TIME END as TXNDATE, a.txnrefno, TXNTYPE, TXNSUBTYPE, TXNMODE, TXNAMOUNT, INOUT, BRANCHCODE, CURRENCY, EXCHANGERATE,REMARKS,
		PURPOSE, CPNAME1, IMPORTED_DATE, CPNAME2, CPNAME3, CPADDRESS1, CPADDRESS2, CPADDRESS3, CORRESPONDENTBANK, CORRESBANKCOUNTRYCODE,
		CORRESBANKADDRESS1, CORRESBANKADDRESS2, CORRESBANKADDRESS3, PRODUCTTYPE, INCEPTIONDATE, MATUITYDATE, TXNNATURE, FUNDSSOURCE, FXAMOUNT,
		A.SOURCE, INPUTDATE, DEBIT_CREDIT, BENEFICIARYNAME1, BENEFICIARYNAME2, BENEFICIARYNAME3, BENEFICIARY_ACCOUNTNO, BENEFICIARY_NAME_FLAG, 
		BENEFICIARYADDRESS1, BENEFICIARYADDRESS2, BENEFICIARYADDRESS3, b.accountid,OPACCOUNTNO, SRCTXNTYPE, SRC_TXN_REFNO, cpaccountno, A.AccountNumber,
			STOCKREFNO, NOOFSHARES, NETASSETVALUE, REGION, convert(date, TXN_DATE_TIME ) txn_date_time, RUNID, RUNDATE
from (

/*************/
/*** DTDPM ***/
/*************/

select 
	 [TXNDATE]      ,[TXNREFNO]      ,'DTDPM' AS TXNTYPE      ,[TXNSUBTYPE]      ,[TXNMODE]      ,[TXNAMOUNT]      ,[INOUT]      ,a.[BRANCHCODE]      ,a.[CURRENCY]      ,[EXCHANGERATE]      ,[PURPOSE]      ,[CPNAME1]      ,a.[IMPORTED_DATE]      ,[CPNAME2]      ,[CPNAME3]      ,[CPINSTITUTION]      ,[CPINSTITUTIONCOUNTRY]      ,[CPADDRESS1]      ,[CPADDRESS2]      ,[CPADDRESS3]      ,[CORRESPONDENTBANK]      ,[CORRESBANKCOUNTRYCODE]      ,[CORRESBANKADDRESS1]      ,[CORRESBANKADDRESS2]      ,[CORRESBANKADDRESS3]      ,[INTERMEDIATORYINST]      ,[INTERMEDIATORYINSTCOUNTRY]      ,[INTERMEDIATORYINSTADDRESS1]      ,[INTERMEDIATORYINSTADDRESS2]      ,[INTERMEDIATORYINSTADDRESS3]      ,[PRODUCTTYPE]      ,[PRODUCTOWNERNAME1]      ,[PRODUCTOWNERNAME2]      ,[PRODUCTOWNERNAME3]      ,[PRODUCTOWNERADDRESS1]      ,[PRODUCTOWNERADDRESS2]      ,[PRODUCTOWNERADDRESS3]      ,[INCEPTIONDATE]      ,[MATUITYDATE]      ,[NARRATION]      ,[TXNNATURE]      ,[FUNDSSOURCE]      ,[FXAMOUNT]      ,[POSTINGGROUPID]      ,[POSTINGSEQNO]      ,a.[SOURCE]      ,[INPUTDATE]      ,[CERTIFIEDDOCUMENTS]      ,[REGULARDOCUMENTS]      ,[TXNFORBRANCH]      ,[BSRCODE]      ,[DEBIT_CREDIT]      ,[BENEFICIARYNAME1]      ,[BENEFICIARYNAME2]      ,[BENEFICIARYNAME3]      ,[BENEFICIARYADDRESS1]      ,[BENEFICIARYADDRESS2]      ,[BENEFICIARYADDRESS3]      ,a.[ACCOUNTID]      ,[REMARKS]      ,[OPBRANCHNAME]      ,[OPACCOUNTNO]      ,[DEALNO]      ,[SRCTXNTYPE]      ,[OTHERACCOUNT]      ,[BENEFICIARY_TINNO]      ,[BENEFICIARYCOUNTRY]      ,[REASONCODE]      ,a.[FIRST_IMPORTED_DATE]      ,[SRC_TXN_REFNO]      ,[cpaccountno]      ,a.[EXPORTED_DATE]      ,a.[ETL_FLAG]      ,[pop_benificiaryaddress]      ,[pop_benificiaryBOD]      ,[OTHERACCOUNTNO]      ,[SBCRefNoDetail]      ,[OTHERACCOUNTBRANCH]      ,[pop_benificiary]      ,[SBCREFNO]      ,[PO_GROUPID]      ,[SRC_TXNTYPE]      ,[customerno]      ,[CardNumber]      ,a.[AccountNumber]      ,[STOCKREFNO]      ,[AMOUNTOFCLAIM]      ,[NOOFSHARES]      ,[NETASSETVALUE]      ,[BENEFICIARY_CUSTOMERREFNO]      ,[BENEFICIARY_ACCOUNTNO]      ,[BENEFICIARY_DATEOFBIRTH]      ,[BENEFICIARY_PLACEOFBIRTH]      ,[BENEFICIARY_IDType]      ,[BENEFICIARY_IDNo]      ,[BENEFICIARY_TelNo]     ,[BENEFICIARY_NatureofBusiness]      ,[SUSPICION_CUSTOMERREFNO]      ,[SUSPICION_NAME1]      ,[SUSPICION_NAME2]      ,[SUSPICION_NAME3]      ,[SUSPICION_ADDRESS1]      ,[SUSPICION_ADDRESS2]      ,[SUSPICION_ADDRESS3]      ,[SUSPICION_ACCOUNTNO]      ,[SUSPICION_DATEOFBIRTH]      ,[SUSPICION_PLACEOFBIRTH]      ,[SUSPICION_NATIONALITY]      ,[SUSPICION_IDType]      ,[SUSPICION_IDNo]     ,[SUSPICION_TelNo]      ,[SUSPICION_NatureofBusiness]      ,[TRANSACTOR_CUSTOMERREFNO]      ,[TRANSACTOR_NAME1]      ,[TRANSACTOR_NAME2]      ,[TRANSACTOR_NAME3]      ,[TRANSACTOR_ADDRESS1]      ,[TRANSACTOR_ADDRESS2]      ,[TRANSACTOR_ADDRESS3]      ,[TRANSACTOR_ACCOUNTNO]      ,[CPCUSTOMERREFNO]      ,[OP_CUSTOMERREFNO]      ,[OP_NAME1]      ,[OP_NAME2]      ,[OP_NAME3]      ,[OP_ADDRESS1]      ,[OP_ADDRESS2]      ,[OP_ADDRESS3]      ,[ISSUER_CUSTOMERREFNO]      ,[ISSUER_NAME1]      ,[ISSUER_NAME2]      ,[ISSUER_NAME3]      ,[ISSUER_ADDRESS1]      ,[ISSUER_ADDRESS2]      ,[ISSUER_ADDRESS3]      ,[ISSUER_ACCOUNTNO]      ,[BENEFICIARY_NAME_FLAG]      ,[CP_NAME_FLAG]      ,[OP_NAME_FLAG]      ,[ISSUER_NAME_FLAG]      ,[TRANSACTOR_NAME_FLAG]      ,[SUSPICIOUS_ACTIVITY_CODE]      ,[CPCUSTTYPE]      ,[REGION]      ,[TXN_DATE_TIME]      ,a.[RUNID]   ,a.[RUNDATE],LAST_RENEWED_DATE,ACCOUNT_OPENED_dATE
	from ETL_AML_TRANSACTION a
	left join aml_account b on a.AccountNumber = b.ACCOUNTNUMBER 
	where txntype = 'cpmd' and b.ACCOUNTTYPE in ('901','902','903','904','906','907','908','909','911','912','913','914')

/*******************/
/*** END - DTDPM ***/
/*******************/

UNION

/*******************/
/**** ROLLOVER *****/
/*******************/
	SELECT * 
	FROM ETL_AML_TRANSACTION 
	WHERE TXNTYPE LIKE '%TD%' AND TXNAMOUNT > 500000 AND ACCOUNTNUMBER NOT IN
	(
	  SELECT ACCOUNTNUMBER 
	  FROM 
		(
		  SELECT ROW_NUMBER() OVER (PARTITION BY ACCOUNTNUMBER,TXNDATE ORDER BY ACCOUNTNUMBER)RN, * 
		  FROM 
		  (
			SELECT * 
			FROM ETL_AML_TRANSACTION 
			WHERe TXNTYPE LIKE '%TD%'
		  ) A 
		) A
	  WHERE RN > 1
	)

/**********************/
/*** END - ROLLOVER ***/
/**********************/

UNION

/*************/
/*** LCYs ****/
/*************/



/* ADDED: 11/06/2023 */
-- LCY DEPOSIT PRODUCT (D360 & PMT)
-- REMOVED/DISREGARD TRANSACTION THAT HAS AN FTRQ TRANSACTIONS




SELECT 
b.TXNDATE ,b.TXNREFNO ,b.TXNTYPE ,b.TXNSUBTYPE ,b.TXNMODE ,b.TXNAMOUNT ,b.INOUT ,b.BRANCHCODE ,b.CURRENCY ,b.EXCHANGERATE
,b.PURPOSE ,b.CPNAME1 ,b.IMPORTED_DATE ,b.CPNAME2 ,b.CPNAME3 ,b.CPINSTITUTION ,b.CPINSTITUTIONCOUNTRY ,b.CPADDRESS1 ,b.CPADDRESS2 ,b.CPADDRESS3
,b.CORRESPONDENTBANK ,b.CORRESBANKCOUNTRYCODE ,b.CORRESBANKADDRESS1 ,b.CORRESBANKADDRESS2 ,b.CORRESBANKADDRESS3 ,b.INTERMEDIATORYINST ,b.INTERMEDIATORYINSTCOUNTRY
,b.INTERMEDIATORYINSTADDRESS1 ,b.INTERMEDIATORYINSTADDRESS2 ,b.INTERMEDIATORYINSTADDRESS3 ,b.PRODUCTTYPE ,b.PRODUCTOWNERNAME1 ,b.PRODUCTOWNERNAME2 
,b.PRODUCTOWNERNAME3 ,b.PRODUCTOWNERADDRESS1 ,b.PRODUCTOWNERADDRESS2 ,b.PRODUCTOWNERADDRESS3 ,b.INCEPTIONDATE ,b.MATUITYDATE ,b.NARRATION ,b.TXNNATURE
,b.FUNDSSOURCE ,b.FXAMOUNT ,b.POSTINGGROUPID ,b.POSTINGSEQNO ,b.SOURCE ,b.INPUTDATE ,b.CERTIFIEDDOCUMENTS ,b.REGULARDOCUMENTS ,b.TXNFORBRANCH ,b.BSRCODE
,b.DEBIT_CREDIT ,b.BENEFICIARYNAME1 ,b.BENEFICIARYNAME2 ,b.BENEFICIARYNAME3 ,b.BENEFICIARYADDRESS1 ,b.BENEFICIARYADDRESS2 ,b.BENEFICIARYADDRESS3 ,b.ACCOUNTID
,b.REMARKS ,b.OPBRANCHNAME ,b.OPACCOUNTNO ,b.DEALNO ,b.SRCTXNTYPE ,b.OTHERACCOUNT ,b.BENEFICIARY_TINNO ,b.BENEFICIARYCOUNTRY ,b.REASONCODE ,b.FIRST_IMPORTED_DATE
,b.SRC_TXN_REFNO ,b.cpaccountno ,b.EXPORTED_DATE ,b.ETL_FLAG ,b.pop_benificiaryaddress ,b.pop_benificiaryBOD ,b.OTHERACCOUNTNO ,b.SBCRefNoDetail
,b.OTHERACCOUNTBRANCH ,b.pop_benificiary ,b.SBCREFNO ,b.PO_GROUPID ,b.SRC_TXNTYPE ,b.customerno ,b.CardNumber ,b.AccountNumber ,b.STOCKREFNO ,b.AMOUNTOFCLAIM
,b.NOOFSHARES ,b.NETASSETVALUE ,b.BENEFICIARY_CUSTOMERREFNO ,b.BENEFICIARY_ACCOUNTNO ,b.BENEFICIARY_DATEOFBIRTH ,b.BENEFICIARY_PLACEOFBIRTH ,b.BENEFICIARY_IDType
,b.BENEFICIARY_IDNo ,b.BENEFICIARY_TelNo ,b.BENEFICIARY_NatureofBusiness ,b.SUSPICION_CUSTOMERREFNO ,b.SUSPICION_NAME1 ,b.SUSPICION_NAME2 ,b.SUSPICION_NAME3 
,b.SUSPICION_ADDRESS1 ,b.SUSPICION_ADDRESS2 ,b.SUSPICION_ADDRESS3 ,b.SUSPICION_ACCOUNTNO ,b.SUSPICION_DATEOFBIRTH ,b.SUSPICION_PLACEOFBIRTH ,b.SUSPICION_NATIONALITY
,b.SUSPICION_IDType ,b.SUSPICION_IDNo ,b.SUSPICION_TelNo ,b.SUSPICION_NatureofBusiness ,b.TRANSACTOR_CUSTOMERREFNO ,b.TRANSACTOR_NAME1 ,b.TRANSACTOR_NAME2 
,b.TRANSACTOR_NAME3 ,b.TRANSACTOR_ADDRESS1 ,b.TRANSACTOR_ADDRESS2 ,b.TRANSACTOR_ADDRESS3 ,b.TRANSACTOR_ACCOUNTNO ,b.CPCUSTOMERREFNO ,b.OP_CUSTOMERREFNO
,b.OP_NAME1 ,b.OP_NAME2 ,b.OP_NAME3 ,b.OP_ADDRESS1 ,b.OP_ADDRESS2 ,b.OP_ADDRESS3 ,b.ISSUER_CUSTOMERREFNO ,b.ISSUER_NAME1 ,b.ISSUER_NAME2 ,b.ISSUER_NAME3
,b.ISSUER_ADDRESS1 ,b.ISSUER_ADDRESS2 ,b.ISSUER_ADDRESS3 ,b.ISSUER_ACCOUNTNO ,b.BENEFICIARY_NAME_FLAG ,b.CP_NAME_FLAG ,b.OP_NAME_FLAG ,b.ISSUER_NAME_FLAG
,b.TRANSACTOR_NAME_FLAG ,b.SUSPICIOUS_ACTIVITY_CODE ,b.CPCUSTTYPE ,b.REGION ,b.TXN_DATE_TIME ,b.RUNID ,b.RUNDATE ,b.last_renewed_date ,b.account_opened_date

FROM
	( 
	  select * 
	  from
		(
		  select row_number() over (partition by accountnumber,txntype order by accountnumber)rntype,* 
		  FROM 
			(
			  select * 
			  from ETL_AML_TRANSACTION 
			  where AccountNumber in
				(
					select AccountNumber from 
					(
						select row_number() over (partition by accountnumber,txndate,txnsubtype order by accountnumber)rn,*
						from ETL_AML_TRANSACTION 
						where AccountNumber in
						(
						  select accountnumber 
						  from 
							( 
								select AccountNumber, COUNT(accountnumber) as rn
								from ETL_AML_TRANSACTION 
								where txntype like '%td%' and txnamount > 500000 --AND TXNSUBTYPE = 'PMT' --and producttype <> 'ftrq'
								--and AccountNumber = '234120001042'
								group by AccountNumber

							) a 
						  where rn = 3 --and AccountNumber = '234120001042'
						) and txntype like '%td%' and txnamount > 500000 AND TXNSUBTYPE = 'PMT' and producttype <> 'ftrq'
					) a
					where rn > 2
				) and txnamount > 500000 and txntype like '%td%'
			) a
		) a 
		where rntype = 2 and txntype = 'DTDYK'
	) A 
LEFT JOIN (SELECT * FROM ETL_AML_TRANSACTION WHERE TXNTYPE = 'DTDPD' ) B ON A.ACCOUNTNUMBER = B.ACCOUNTNUMBER

/******************/
/*** END - LCYs ***/
/******************/


UNION


/*******************/
/*** FTR - DPAs ****/
/*******************/
-- gets all DPA, not reportable DPA will be used for next transaction for last_renewed_date reference

select * from ETL_AML_TRANSACTION where txntype = 'dtdpd' and TXNSUBTYPE = 'DPA' 

/******************/
/*** END - DPAs ***/
/******************/


UNION


/************************/
/*** INITIAL DEPOSIT ****/
/************************/
-- REVISED INITIAL DEPOSIT "NEW"
-- gets not reportable transaction will be used for next transaction for last_renewed_date reference

select 
* from ETL_AML_TRANSACTION 
where AccountNumber in (
	select AccountNumber 
	from (
		select count(accountnumber) CountAcc, AccountNumber 
		from ETL_AML_TRANSACTION
		where TXNSUBTYPE = 'PMT'
		group by AccountNumber
		having count(accountnumber) = 2 
	) a
) 
and TXNTYPE like '%td%' and TXNAMOUNT <= 500000 and TXNSUBTYPE = 'PMT' and TXNTYPE <> 'dtdpd'

/******************************/
/*** END - INITIAL DEPOSIT ****/
/******************************/


UNION


/***************************************************/
/*** INITIAL DEPOSIT (FTR-ADDITIONAL PLACEMENT) ****/
/***************************************************/
--GETS ONLY THE DTDYK FOR LAST_RENEWED_DATE REFERENCE

select
a.*
--a.AccountNumber, 
--a.TXNREFNO as A_TXNREFNO, a.TXNTYPE as A_TXNTYPE, a.TXNAMOUNT as A_TXNAMOUNT, a.INOUT as A_INOUT, a.last_renewed_date as LRD,
--b.TXNREFNO as B_TXNREFNO, B.TXNTYPE as B_TXNTYPE, B.TXNAMOUNT as B_TXNAMOUNT, B.INOUT as B_INOUT,b.last_renewed_date as LRD,
--c.TXNREFNO as C_TXNREFNO, c.TXNTYPE as C_TXNTYPE, c.TXNAMOUNT as C_TXNAMOUNT, B.INOUT as C_INOUT, c.last_renewed_date as LRD


from
(
	SELECT *
	from ETL_AML_TRANSACTION
	where AccountNumber in
	(
		select AccountNumber from
		(
			select COUNT(TXNTYPE) as DTDPD#, AccountNumber
			from ETL_AML_TRANSACTION
			where TXNTYPE = 'dtdpd' and TXNSUBTYPE = 'PMT'
			group by AccountNumber, TXNDATE 
			having COUNT(TXNTYPE) = 2
		) a
	) and TXNTYPE = 'DTDYK'
) a
inner join ETL_AML_TRANSACTION b on b.AccountNumber = a.AccountNumber  and b.TXNAMOUNT = a.TXNAMOUNT and b.TXNTYPE <> a.TXNTYPE
inner join ETL_AML_TRANSACTION c on c.AccountNumber = a.AccountNumber and c.TXNAMOUNT <> a.TXNAMOUNT 
where b.TXNAMOUNT <= 500000 and c.TXNAMOUNT+b.TXNAMOUNT <= 500000 

/*********************************************************/
/*** END - INITIAL DEPOSIT (FTR-ADDITIONAL PLACEMENT) ****/
/*********************************************************/


UNION


/*******************************/
/*** FTR - INITIAL REPORTING ***/
/*******************************/

-- NEW FTR - INITIAL REPORTING - 04262023
-- REVISED @ 10-20-2023

select * from ETL_AML_TRANSACTION 
where AccountNumber in 
(
	select AccountNumber 
	from 
	(
		select count(accountnumber) CountAcc, AccountNumber 
		from 
		(
			select a.* from ETL_AML_TRANSACTION a
			left join 
			(
				select * from 
				(
					select ROW_NUMBER() over (partition by accountnumber order by txndate desc) rn,* from AML_TRANSACTION
					where AccountNumber not in 
					(
						select AccountNumber from 
						(
							select AccountNumber,count(TXNAMOUNT) as Flag1 from AML_TRANSACTION
							GROUP BY AccountNumber, TXNAMOUNT
							HAVING TXNAMOUNT > 500000
						) x 
					)
				) a
				where rn = 1 and TXNTYPE like '%td%'
			) b on b.AccountNumber = a.AccountNumber 
			where b.TXNAMOUNT <= 500000 and b.TXNTYPE like '%td%' 
		) a
		group by AccountNumber
		having count(accountnumber) = 2
	) a
) 
and TXNSUBTYPE = 'PMT' and TXNMODE = 'CR' and TXNAMOUNT > 500000 

/*************************************/
/*** END - FTR - INITIAL REPORTING ***/
/*************************************/


UNION


/************************************************/
/*** FTR - ADDITONAL PLACEMENT (SAME AMOUNTS) ***/
/************************************************/

select
--'FTR-AP BAL+AP > 500K (SAME AMOUNTS)' as TD_SCENARIO,
TXNDATE ,TXNREFNO ,TXNTYPE ,TXNSUBTYPE ,TXNMODE ,TXNAMOUNT, INOUT ,BRANCHCODE ,CURRENCY ,EXCHANGERATE
,PURPOSE ,CPNAME1 ,IMPORTED_DATE ,CPNAME2 ,CPNAME3 ,CPINSTITUTION ,CPINSTITUTIONCOUNTRY ,CPADDRESS1 ,CPADDRESS2 ,CPADDRESS3
,CORRESPONDENTBANK ,CORRESBANKCOUNTRYCODE ,CORRESBANKADDRESS1 ,CORRESBANKADDRESS2 ,CORRESBANKADDRESS3 ,INTERMEDIATORYINST ,INTERMEDIATORYINSTCOUNTRY
,INTERMEDIATORYINSTADDRESS1 ,INTERMEDIATORYINSTADDRESS2 ,INTERMEDIATORYINSTADDRESS3 ,PRODUCTTYPE ,PRODUCTOWNERNAME1 ,PRODUCTOWNERNAME2 
,PRODUCTOWNERNAME3 ,PRODUCTOWNERADDRESS1 ,PRODUCTOWNERADDRESS2 ,PRODUCTOWNERADDRESS3 ,INCEPTIONDATE ,MATUITYDATE ,NARRATION ,TXNNATURE
,FUNDSSOURCE ,FXAMOUNT ,POSTINGGROUPID ,POSTINGSEQNO ,SOURCE ,INPUTDATE ,CERTIFIEDDOCUMENTS ,REGULARDOCUMENTS ,TXNFORBRANCH ,BSRCODE
,DEBIT_CREDIT ,BENEFICIARYNAME1 ,BENEFICIARYNAME2 ,BENEFICIARYNAME3 ,BENEFICIARYADDRESS1 ,BENEFICIARYADDRESS2 ,BENEFICIARYADDRESS3 ,ACCOUNTID
,REMARKS ,OPBRANCHNAME ,OPACCOUNTNO ,DEALNO ,SRCTXNTYPE ,OTHERACCOUNT ,BENEFICIARY_TINNO ,BENEFICIARYCOUNTRY ,REASONCODE ,FIRST_IMPORTED_DATE
,SRC_TXN_REFNO ,cpaccountno ,EXPORTED_DATE ,ETL_FLAG ,pop_benificiaryaddress ,pop_benificiaryBOD ,OTHERACCOUNTNO ,SBCRefNoDetail
,OTHERACCOUNTBRANCH ,pop_benificiary ,SBCREFNO ,PO_GROUPID ,SRC_TXNTYPE ,customerno ,CardNumber ,AccountNumber ,STOCKREFNO ,AMOUNTOFCLAIM
,NOOFSHARES ,NETASSETVALUE ,BENEFICIARY_CUSTOMERREFNO ,BENEFICIARY_ACCOUNTNO ,BENEFICIARY_DATEOFBIRTH ,BENEFICIARY_PLACEOFBIRTH ,BENEFICIARY_IDType
,BENEFICIARY_IDNo ,BENEFICIARY_TelNo ,BENEFICIARY_NatureofBusiness ,SUSPICION_CUSTOMERREFNO ,SUSPICION_NAME1 ,SUSPICION_NAME2 ,SUSPICION_NAME3 
,SUSPICION_ADDRESS1 ,SUSPICION_ADDRESS2 ,SUSPICION_ADDRESS3 ,SUSPICION_ACCOUNTNO ,SUSPICION_DATEOFBIRTH ,SUSPICION_PLACEOFBIRTH ,SUSPICION_NATIONALITY
,SUSPICION_IDType ,SUSPICION_IDNo ,SUSPICION_TelNo ,SUSPICION_NatureofBusiness ,TRANSACTOR_CUSTOMERREFNO ,TRANSACTOR_NAME1 ,TRANSACTOR_NAME2 
,TRANSACTOR_NAME3 ,TRANSACTOR_ADDRESS1 ,TRANSACTOR_ADDRESS2 ,TRANSACTOR_ADDRESS3 ,TRANSACTOR_ACCOUNTNO ,CPCUSTOMERREFNO ,OP_CUSTOMERREFNO
,OP_NAME1 ,OP_NAME2 ,OP_NAME3 ,OP_ADDRESS1 ,OP_ADDRESS2 ,OP_ADDRESS3 ,ISSUER_CUSTOMERREFNO ,ISSUER_NAME1 ,ISSUER_NAME2 ,ISSUER_NAME3
,ISSUER_ADDRESS1 ,ISSUER_ADDRESS2 ,ISSUER_ADDRESS3 ,ISSUER_ACCOUNTNO ,BENEFICIARY_NAME_FLAG ,CP_NAME_FLAG ,OP_NAME_FLAG ,ISSUER_NAME_FLAG
,TRANSACTOR_NAME_FLAG ,SUSPICIOUS_ACTIVITY_CODE ,CPCUSTTYPE ,REGION ,TXN_DATE_TIME ,RUNID ,RUNDATE ,last_renewed_date ,account_opened_date

from (
select
--a.AccountNumber, 
--a.TXNREFNO as A_TXNREFNO, a.TXNTYPE as A_TXNTYPE, a.TXNAMOUNT as A_TXNAMOUNT, a.INOUT as A_INOUT,
--b.TXNREFNO as B_TXNREFNO, B.TXNTYPE as B_TXNTYPE, B.TXNAMOUNT as B_TXNAMOUNT, B.INOUT as B_INOUT,
--c.TXNREFNO as C_TXNREFNO, c.TXNTYPE as C_TXNTYPE, c.TXNAMOUNT as C_TXNAMOUNT, B.INOUT as C_INOUT 
ROW_NUMBER() OVER (partition by c.accountnumber, c.txnamount order by c.accountnumber) as rn,
c.TXNDATE ,c.TXNREFNO ,c.TXNTYPE ,c.TXNSUBTYPE ,c.TXNMODE ,c.TXNAMOUNT + b.TXNAMOUNT as TXNAMOUNT ,c.INOUT ,c.BRANCHCODE ,c.CURRENCY ,c.EXCHANGERATE
,c.PURPOSE ,c.CPNAME1 ,c.IMPORTED_DATE ,c.CPNAME2 ,c.CPNAME3 ,c.CPINSTITUTION ,c.CPINSTITUTIONCOUNTRY ,c.CPADDRESS1 ,c.CPADDRESS2 ,c.CPADDRESS3
,c.CORRESPONDENTBANK ,c.CORRESBANKCOUNTRYCODE ,c.CORRESBANKADDRESS1 ,c.CORRESBANKADDRESS2 ,c.CORRESBANKADDRESS3 ,c.INTERMEDIATORYINST ,c.INTERMEDIATORYINSTCOUNTRY
,c.INTERMEDIATORYINSTADDRESS1 ,c.INTERMEDIATORYINSTADDRESS2 ,c.INTERMEDIATORYINSTADDRESS3 ,c.PRODUCTTYPE ,c.PRODUCTOWNERNAME1 ,c.PRODUCTOWNERNAME2 
,c.PRODUCTOWNERNAME3 ,c.PRODUCTOWNERADDRESS1 ,c.PRODUCTOWNERADDRESS2 ,c.PRODUCTOWNERADDRESS3 ,c.INCEPTIONDATE ,c.MATUITYDATE ,c.NARRATION ,c.TXNNATURE
,c.FUNDSSOURCE ,c.FXAMOUNT ,c.POSTINGGROUPID ,c.POSTINGSEQNO ,c.SOURCE ,c.INPUTDATE ,c.CERTIFIEDDOCUMENTS ,c.REGULARDOCUMENTS ,c.TXNFORBRANCH ,c.BSRCODE
,c.DEBIT_CREDIT ,c.BENEFICIARYNAME1 ,c.BENEFICIARYNAME2 ,c.BENEFICIARYNAME3 ,c.BENEFICIARYADDRESS1 ,c.BENEFICIARYADDRESS2 ,c.BENEFICIARYADDRESS3 ,c.ACCOUNTID
,c.REMARKS ,c.OPBRANCHNAME ,c.OPACCOUNTNO ,c.DEALNO ,c.SRCTXNTYPE ,c.OTHERACCOUNT ,c.BENEFICIARY_TINNO ,c.BENEFICIARYCOUNTRY ,c.REASONCODE ,c.FIRST_IMPORTED_DATE
,c.SRC_TXN_REFNO ,c.cpaccountno ,c.EXPORTED_DATE ,c.ETL_FLAG ,c.pop_benificiaryaddress ,c.pop_benificiaryBOD ,c.OTHERACCOUNTNO ,c.SBCRefNoDetail
,c.OTHERACCOUNTBRANCH ,c.pop_benificiary ,c.SBCREFNO ,c.PO_GROUPID ,c.SRC_TXNTYPE ,c.customerno ,c.CardNumber ,c.AccountNumber ,c.STOCKREFNO ,c.AMOUNTOFCLAIM
,c.NOOFSHARES ,c.NETASSETVALUE ,c.BENEFICIARY_CUSTOMERREFNO ,c.BENEFICIARY_ACCOUNTNO ,c.BENEFICIARY_DATEOFBIRTH ,c.BENEFICIARY_PLACEOFBIRTH ,c.BENEFICIARY_IDType
,c.BENEFICIARY_IDNo ,c.BENEFICIARY_TelNo ,c.BENEFICIARY_NatureofBusiness ,c.SUSPICION_CUSTOMERREFNO ,c.SUSPICION_NAME1 ,c.SUSPICION_NAME2 ,c.SUSPICION_NAME3 
,c.SUSPICION_ADDRESS1 ,c.SUSPICION_ADDRESS2 ,c.SUSPICION_ADDRESS3 ,c.SUSPICION_ACCOUNTNO ,c.SUSPICION_DATEOFBIRTH ,c.SUSPICION_PLACEOFBIRTH ,c.SUSPICION_NATIONALITY
,c.SUSPICION_IDType ,c.SUSPICION_IDNo ,c.SUSPICION_TelNo ,c.SUSPICION_NatureofBusiness ,c.TRANSACTOR_CUSTOMERREFNO ,c.TRANSACTOR_NAME1 ,c.TRANSACTOR_NAME2 
,c.TRANSACTOR_NAME3 ,c.TRANSACTOR_ADDRESS1 ,c.TRANSACTOR_ADDRESS2 ,c.TRANSACTOR_ADDRESS3 ,c.TRANSACTOR_ACCOUNTNO ,c.CPCUSTOMERREFNO ,c.OP_CUSTOMERREFNO
,c.OP_NAME1 ,c.OP_NAME2 ,c.OP_NAME3 ,c.OP_ADDRESS1 ,c.OP_ADDRESS2 ,c.OP_ADDRESS3 ,c.ISSUER_CUSTOMERREFNO ,c.ISSUER_NAME1 ,c.ISSUER_NAME2 ,c.ISSUER_NAME3
,c.ISSUER_ADDRESS1 ,c.ISSUER_ADDRESS2 ,c.ISSUER_ADDRESS3 ,c.ISSUER_ACCOUNTNO ,c.BENEFICIARY_NAME_FLAG ,c.CP_NAME_FLAG ,c.OP_NAME_FLAG ,c.ISSUER_NAME_FLAG
,c.TRANSACTOR_NAME_FLAG ,c.SUSPICIOUS_ACTIVITY_CODE ,c.CPCUSTTYPE ,c.REGION ,c.TXN_DATE_TIME ,c.RUNID ,c.RUNDATE ,c.last_renewed_date ,c.account_opened_date

from 
(
	SELECT *
	from ETL_AML_TRANSACTION
	where AccountNumber in
	(
		select AccountNumber from
		(
			select COUNT(TXNTYPE) as DTDPD#, AccountNumber
			from ETL_AML_TRANSACTION
			where TXNTYPE = 'dtdpd' and TXNSUBTYPE = 'PMT'
			group by AccountNumber, TXNDATE 
			having COUNT(TXNTYPE) = 2
		) a --where AccountNumber = '001121026559'
	) and TXNTYPE = 'DTDYK' 
) a
inner join ETL_AML_TRANSACTION b on b.AccountNumber = a.AccountNumber  and b.TXNAMOUNT = a.TXNAMOUNT and b.TXNTYPE <> a.TXNTYPE
inner join ETL_AML_TRANSACTION c on c.AccountNumber = a.AccountNumber and c.TXNAMOUNT = b.TXNAMOUNT and b.TXNTYPE = c.TXNTYPE and c.TXNREFNO <> b.TXNREFNO
where 
--b.TXNAMOUNT >= 500000 and 
c.TXNAMOUNT+b.TXNAMOUNT > 500000 
) a 
where rn = 1 
and AccountNumber not in  --NEWLY ADDED PARAMETER
	(
		select AccountNumber from 
		(
			select AccountNumber,count(TXNAMOUNT) as Flag1 from AML_TRANSACTION
			GROUP BY AccountNumber, TXNAMOUNT
			HAVING TXNAMOUNT > 500000
		) x  --where AccountNumber = '052120000790'
	)

/******************************************************/
/*** END - FTR - ADDITONAL PLACEMENT (SAME AMOUNTS) ***/
/******************************************************/


UNION


/*******************************************************/
/*** ADDITIONAL PLACEMENT FILTERING PROCESS WITH FTR ***/
/*******************************************************/


-- w/o FTRQ

select
--a.AccountNumber,
--a.TXNREFNO as A_TXNREFNO, a.TXNTYPE as A_TXNTYPE, a.txnsubtype as A_TXNSUBTYPE, a.TXNAMOUNT as A_TXNAMOUNT, a.INOUT as A_INOUT, a.last_renewed_date as LRD,
--b.TXNREFNO as B_TXNREFNO, B.TXNTYPE as B_TXNTYPE, b.txnsubtype as B_TXNSUBTYPE, B.TXNAMOUNT as B_TXNAMOUNT, B.INOUT as B_INOUT,b.last_renewed_date as LRD,
--c.TXNREFNO as C_TXNREFNO, c.TXNTYPE as C_TXNTYPE, c.txnsubtype as C_TXNSUBTYPE, c.TXNAMOUNT as C_TXNAMOUNT, B.INOUT as C_INOUT, c.last_renewed_date as LRD

--'FTR - ADDITIONAL PLACEMENT + REGULAR AP' as TD_SCENARIO,
c.TXNDATE ,a.TXNREFNO ,c.TXNTYPE ,c.TXNSUBTYPE ,c.TXNMODE ,c.TXNAMOUNT + b.TXNAMOUNT as TXNAMOUNT ,c.INOUT ,c.BRANCHCODE ,c.CURRENCY ,c.EXCHANGERATE
,c.PURPOSE ,c.CPNAME1 ,c.IMPORTED_DATE ,c.CPNAME2 ,c.CPNAME3 ,c.CPINSTITUTION ,c.CPINSTITUTIONCOUNTRY ,c.CPADDRESS1 ,c.CPADDRESS2 ,c.CPADDRESS3
,c.CORRESPONDENTBANK ,c.CORRESBANKCOUNTRYCODE ,c.CORRESBANKADDRESS1 ,c.CORRESBANKADDRESS2 ,c.CORRESBANKADDRESS3 ,c.INTERMEDIATORYINST ,c.INTERMEDIATORYINSTCOUNTRY
,c.INTERMEDIATORYINSTADDRESS1 ,c.INTERMEDIATORYINSTADDRESS2 ,c.INTERMEDIATORYINSTADDRESS3 ,c.PRODUCTTYPE ,c.PRODUCTOWNERNAME1 ,c.PRODUCTOWNERNAME2 
,c.PRODUCTOWNERNAME3 ,c.PRODUCTOWNERADDRESS1 ,c.PRODUCTOWNERADDRESS2 ,c.PRODUCTOWNERADDRESS3 ,c.INCEPTIONDATE ,c.MATUITYDATE ,c.NARRATION ,c.TXNNATURE
,c.FUNDSSOURCE ,c.FXAMOUNT ,c.POSTINGGROUPID ,c.POSTINGSEQNO ,c.SOURCE ,c.INPUTDATE ,c.CERTIFIEDDOCUMENTS ,c.REGULARDOCUMENTS ,c.TXNFORBRANCH ,c.BSRCODE
,c.DEBIT_CREDIT ,c.BENEFICIARYNAME1 ,c.BENEFICIARYNAME2 ,c.BENEFICIARYNAME3 ,c.BENEFICIARYADDRESS1 ,c.BENEFICIARYADDRESS2 ,c.BENEFICIARYADDRESS3 ,c.ACCOUNTID
,c.REMARKS ,c.OPBRANCHNAME ,c.OPACCOUNTNO ,c.DEALNO ,c.SRCTXNTYPE ,c.OTHERACCOUNT ,c.BENEFICIARY_TINNO ,c.BENEFICIARYCOUNTRY ,c.REASONCODE ,c.FIRST_IMPORTED_DATE
,c.SRC_TXN_REFNO ,c.cpaccountno ,c.EXPORTED_DATE ,c.ETL_FLAG ,c.pop_benificiaryaddress ,c.pop_benificiaryBOD ,c.OTHERACCOUNTNO ,c.SBCRefNoDetail
,c.OTHERACCOUNTBRANCH ,c.pop_benificiary ,c.SBCREFNO ,c.PO_GROUPID ,c.SRC_TXNTYPE ,c.customerno ,c.CardNumber ,c.AccountNumber ,c.STOCKREFNO ,c.AMOUNTOFCLAIM
,c.NOOFSHARES ,c.NETASSETVALUE ,c.BENEFICIARY_CUSTOMERREFNO ,c.BENEFICIARY_ACCOUNTNO ,c.BENEFICIARY_DATEOFBIRTH ,c.BENEFICIARY_PLACEOFBIRTH ,c.BENEFICIARY_IDType
,c.BENEFICIARY_IDNo ,c.BENEFICIARY_TelNo ,c.BENEFICIARY_NatureofBusiness ,c.SUSPICION_CUSTOMERREFNO ,c.SUSPICION_NAME1 ,c.SUSPICION_NAME2 ,c.SUSPICION_NAME3 
,c.SUSPICION_ADDRESS1 ,c.SUSPICION_ADDRESS2 ,c.SUSPICION_ADDRESS3 ,c.SUSPICION_ACCOUNTNO ,c.SUSPICION_DATEOFBIRTH ,c.SUSPICION_PLACEOFBIRTH ,c.SUSPICION_NATIONALITY
,c.SUSPICION_IDType ,c.SUSPICION_IDNo ,c.SUSPICION_TelNo ,c.SUSPICION_NatureofBusiness ,c.TRANSACTOR_CUSTOMERREFNO ,c.TRANSACTOR_NAME1 ,c.TRANSACTOR_NAME2 
,c.TRANSACTOR_NAME3 ,c.TRANSACTOR_ADDRESS1 ,c.TRANSACTOR_ADDRESS2 ,c.TRANSACTOR_ADDRESS3 ,c.TRANSACTOR_ACCOUNTNO ,c.CPCUSTOMERREFNO ,c.OP_CUSTOMERREFNO
,c.OP_NAME1 ,c.OP_NAME2 ,c.OP_NAME3 ,c.OP_ADDRESS1 ,c.OP_ADDRESS2 ,c.OP_ADDRESS3 ,c.ISSUER_CUSTOMERREFNO ,c.ISSUER_NAME1 ,c.ISSUER_NAME2 ,c.ISSUER_NAME3
,c.ISSUER_ADDRESS1 ,c.ISSUER_ADDRESS2 ,c.ISSUER_ADDRESS3 ,c.ISSUER_ACCOUNTNO ,c.BENEFICIARY_NAME_FLAG ,c.CP_NAME_FLAG ,c.OP_NAME_FLAG ,c.ISSUER_NAME_FLAG
,c.TRANSACTOR_NAME_FLAG ,c.SUSPICIOUS_ACTIVITY_CODE ,c.CPCUSTTYPE ,c.REGION ,c.TXN_DATE_TIME ,c.RUNID ,c.RUNDATE ,c.last_renewed_date ,c.account_opened_date


from
(
	SELECT ROW_NUMBER() OVER (PARTITION BY ACCOUNTNUMBER, TXNDATE, TXNSUBTYPE ORDER BY ACCOUNTNUMBER desc, TXNAMOUNT desc) RN, *
	from ETL_AML_TRANSACTION
	where AccountNumber in
	(
		select ACC#TD from 
		(
			select * from
				(
					select COUNT(TXNTYPE) as DTDPD#, AccountNumber as ACC#TD
					from ETL_AML_TRANSACTION
					where TXNTYPE = 'dtdpd' and TXNSUBTYPE = 'PMT' 
					group by AccountNumber
					having COUNT(TXNTYPE) = 2
				) a
			left join
				( 
					select COUNT(PRODUCTTYPE) as FTRQ#, AccountNumber as ACC#FTRQ 
					from ETL_AML_TRANSACTION
					where PRODUCTTYPE = 'FTRQ'
					GROUP BY AccountNumber
				) b on b.ACC#FTRQ = a.ACC#TD
		) a
		WHERE FTRQ# is NULL --and ACC#TD = '234120001042'
	) and TXNTYPE = 'DTDYK' --and AccountNumber = '234120001042'
) a
inner join ETL_AML_TRANSACTION b on b.AccountNumber = a.AccountNumber  and b.TXNAMOUNT = a.TXNAMOUNT and b.TXNTYPE <> a.TXNTYPE
inner join ETL_AML_TRANSACTION c on c.AccountNumber = a.AccountNumber and c.TXNAMOUNT <> a.TXNAMOUNT 
where c.TXNAMOUNT > 500000 or (b.TXNAMOUNT <= 500000 and c.TXNAMOUNT+b.TXNAMOUNT > 500000)

/*************************************************************/
/*** END - ADDITIONAL PLACEMENT FILTERING PROCESS WITH FTR ***/
/*************************************************************/


UNION


/******************************************/
/*** ADDITIONAL PLACEMENT (SAME AMOUNT) ***/
/******************************************/
select 
TXNDATE ,TXNREFNO ,TXNTYPE ,TXNSUBTYPE ,TXNMODE ,TXNAMOUNT, INOUT ,BRANCHCODE ,CURRENCY ,EXCHANGERATE
,PURPOSE ,CPNAME1 ,IMPORTED_DATE ,CPNAME2 ,CPNAME3 ,CPINSTITUTION ,CPINSTITUTIONCOUNTRY ,CPADDRESS1 ,CPADDRESS2 ,CPADDRESS3
,CORRESPONDENTBANK ,CORRESBANKCOUNTRYCODE ,CORRESBANKADDRESS1 ,CORRESBANKADDRESS2 ,CORRESBANKADDRESS3 ,INTERMEDIATORYINST ,INTERMEDIATORYINSTCOUNTRY
,INTERMEDIATORYINSTADDRESS1 ,INTERMEDIATORYINSTADDRESS2 ,INTERMEDIATORYINSTADDRESS3 ,PRODUCTTYPE ,PRODUCTOWNERNAME1 ,PRODUCTOWNERNAME2 
,PRODUCTOWNERNAME3 ,PRODUCTOWNERADDRESS1 ,PRODUCTOWNERADDRESS2 ,PRODUCTOWNERADDRESS3 ,INCEPTIONDATE ,MATUITYDATE ,NARRATION ,TXNNATURE
,FUNDSSOURCE ,FXAMOUNT ,POSTINGGROUPID ,POSTINGSEQNO ,SOURCE ,INPUTDATE ,CERTIFIEDDOCUMENTS ,REGULARDOCUMENTS ,TXNFORBRANCH ,BSRCODE
,DEBIT_CREDIT ,BENEFICIARYNAME1 ,BENEFICIARYNAME2 ,BENEFICIARYNAME3 ,BENEFICIARYADDRESS1 ,BENEFICIARYADDRESS2 ,BENEFICIARYADDRESS3 ,ACCOUNTID
,REMARKS ,OPBRANCHNAME ,OPACCOUNTNO ,DEALNO ,SRCTXNTYPE ,OTHERACCOUNT ,BENEFICIARY_TINNO ,BENEFICIARYCOUNTRY ,REASONCODE ,FIRST_IMPORTED_DATE
,SRC_TXN_REFNO ,cpaccountno ,EXPORTED_DATE ,ETL_FLAG ,pop_benificiaryaddress ,pop_benificiaryBOD ,OTHERACCOUNTNO ,SBCRefNoDetail
,OTHERACCOUNTBRANCH ,pop_benificiary ,SBCREFNO ,PO_GROUPID ,SRC_TXNTYPE ,customerno ,CardNumber ,AccountNumber ,STOCKREFNO ,AMOUNTOFCLAIM
,NOOFSHARES ,NETASSETVALUE ,BENEFICIARY_CUSTOMERREFNO ,BENEFICIARY_ACCOUNTNO ,BENEFICIARY_DATEOFBIRTH ,BENEFICIARY_PLACEOFBIRTH ,BENEFICIARY_IDType
,BENEFICIARY_IDNo ,BENEFICIARY_TelNo ,BENEFICIARY_NatureofBusiness ,SUSPICION_CUSTOMERREFNO ,SUSPICION_NAME1 ,SUSPICION_NAME2 ,SUSPICION_NAME3 
,SUSPICION_ADDRESS1 ,SUSPICION_ADDRESS2 ,SUSPICION_ADDRESS3 ,SUSPICION_ACCOUNTNO ,SUSPICION_DATEOFBIRTH ,SUSPICION_PLACEOFBIRTH ,SUSPICION_NATIONALITY
,SUSPICION_IDType ,SUSPICION_IDNo ,SUSPICION_TelNo ,SUSPICION_NatureofBusiness ,TRANSACTOR_CUSTOMERREFNO ,TRANSACTOR_NAME1 ,TRANSACTOR_NAME2 
,TRANSACTOR_NAME3 ,TRANSACTOR_ADDRESS1 ,TRANSACTOR_ADDRESS2 ,TRANSACTOR_ADDRESS3 ,TRANSACTOR_ACCOUNTNO ,CPCUSTOMERREFNO ,OP_CUSTOMERREFNO
,OP_NAME1 ,OP_NAME2 ,OP_NAME3 ,OP_ADDRESS1 ,OP_ADDRESS2 ,OP_ADDRESS3 ,ISSUER_CUSTOMERREFNO ,ISSUER_NAME1 ,ISSUER_NAME2 ,ISSUER_NAME3
,ISSUER_ADDRESS1 ,ISSUER_ADDRESS2 ,ISSUER_ADDRESS3 ,ISSUER_ACCOUNTNO ,BENEFICIARY_NAME_FLAG ,CP_NAME_FLAG ,OP_NAME_FLAG ,ISSUER_NAME_FLAG
,TRANSACTOR_NAME_FLAG ,SUSPICIOUS_ACTIVITY_CODE ,CPCUSTTYPE ,REGION ,TXN_DATE_TIME ,RUNID ,RUNDATE ,last_renewed_date ,account_opened_date
from (
select
--a.AccountNumber, 
--a.TXNREFNO as A_TXNREFNO, a.TXNTYPE as A_TXNTYPE, a.TXNAMOUNT as A_TXNAMOUNT, a.INOUT as A_INOUT,
--b.TXNREFNO as B_TXNREFNO, B.TXNTYPE as B_TXNTYPE, B.TXNAMOUNT as B_TXNAMOUNT, B.INOUT as B_INOUT,
--c.TXNREFNO as C_TXNREFNO, c.TXNTYPE as C_TXNTYPE, c.TXNAMOUNT as C_TXNAMOUNT, B.INOUT as C_INOUT 
ROW_NUMBER() OVER (partition by c.accountnumber, c.txnamount order by c.accountnumber) as rn,
c.TXNDATE ,c.TXNREFNO ,c.TXNTYPE ,c.TXNSUBTYPE ,c.TXNMODE ,c.TXNAMOUNT + b.TXNAMOUNT as TXNAMOUNT ,c.INOUT ,c.BRANCHCODE ,c.CURRENCY ,c.EXCHANGERATE
,c.PURPOSE ,c.CPNAME1 ,c.IMPORTED_DATE ,c.CPNAME2 ,c.CPNAME3 ,c.CPINSTITUTION ,c.CPINSTITUTIONCOUNTRY ,c.CPADDRESS1 ,c.CPADDRESS2 ,c.CPADDRESS3
,c.CORRESPONDENTBANK ,c.CORRESBANKCOUNTRYCODE ,c.CORRESBANKADDRESS1 ,c.CORRESBANKADDRESS2 ,c.CORRESBANKADDRESS3 ,c.INTERMEDIATORYINST ,c.INTERMEDIATORYINSTCOUNTRY
,c.INTERMEDIATORYINSTADDRESS1 ,c.INTERMEDIATORYINSTADDRESS2 ,c.INTERMEDIATORYINSTADDRESS3 ,c.PRODUCTTYPE ,c.PRODUCTOWNERNAME1 ,c.PRODUCTOWNERNAME2 
,c.PRODUCTOWNERNAME3 ,c.PRODUCTOWNERADDRESS1 ,c.PRODUCTOWNERADDRESS2 ,c.PRODUCTOWNERADDRESS3 ,c.INCEPTIONDATE ,c.MATUITYDATE ,c.NARRATION ,c.TXNNATURE
,c.FUNDSSOURCE ,c.FXAMOUNT ,c.POSTINGGROUPID ,c.POSTINGSEQNO ,c.SOURCE ,c.INPUTDATE ,c.CERTIFIEDDOCUMENTS ,c.REGULARDOCUMENTS ,c.TXNFORBRANCH ,c.BSRCODE
,c.DEBIT_CREDIT ,c.BENEFICIARYNAME1 ,c.BENEFICIARYNAME2 ,c.BENEFICIARYNAME3 ,c.BENEFICIARYADDRESS1 ,c.BENEFICIARYADDRESS2 ,c.BENEFICIARYADDRESS3 ,c.ACCOUNTID
,c.REMARKS ,c.OPBRANCHNAME ,c.OPACCOUNTNO ,c.DEALNO ,c.SRCTXNTYPE ,c.OTHERACCOUNT ,c.BENEFICIARY_TINNO ,c.BENEFICIARYCOUNTRY ,c.REASONCODE ,c.FIRST_IMPORTED_DATE
,c.SRC_TXN_REFNO ,c.cpaccountno ,c.EXPORTED_DATE ,c.ETL_FLAG ,c.pop_benificiaryaddress ,c.pop_benificiaryBOD ,c.OTHERACCOUNTNO ,c.SBCRefNoDetail
,c.OTHERACCOUNTBRANCH ,c.pop_benificiary ,c.SBCREFNO ,c.PO_GROUPID ,c.SRC_TXNTYPE ,c.customerno ,c.CardNumber ,c.AccountNumber ,c.STOCKREFNO ,c.AMOUNTOFCLAIM
,c.NOOFSHARES ,c.NETASSETVALUE ,c.BENEFICIARY_CUSTOMERREFNO ,c.BENEFICIARY_ACCOUNTNO ,c.BENEFICIARY_DATEOFBIRTH ,c.BENEFICIARY_PLACEOFBIRTH ,c.BENEFICIARY_IDType
,c.BENEFICIARY_IDNo ,c.BENEFICIARY_TelNo ,c.BENEFICIARY_NatureofBusiness ,c.SUSPICION_CUSTOMERREFNO ,c.SUSPICION_NAME1 ,c.SUSPICION_NAME2 ,c.SUSPICION_NAME3 
,c.SUSPICION_ADDRESS1 ,c.SUSPICION_ADDRESS2 ,c.SUSPICION_ADDRESS3 ,c.SUSPICION_ACCOUNTNO ,c.SUSPICION_DATEOFBIRTH ,c.SUSPICION_PLACEOFBIRTH ,c.SUSPICION_NATIONALITY
,c.SUSPICION_IDType ,c.SUSPICION_IDNo ,c.SUSPICION_TelNo ,c.SUSPICION_NatureofBusiness ,c.TRANSACTOR_CUSTOMERREFNO ,c.TRANSACTOR_NAME1 ,c.TRANSACTOR_NAME2 
,c.TRANSACTOR_NAME3 ,c.TRANSACTOR_ADDRESS1 ,c.TRANSACTOR_ADDRESS2 ,c.TRANSACTOR_ADDRESS3 ,c.TRANSACTOR_ACCOUNTNO ,c.CPCUSTOMERREFNO ,c.OP_CUSTOMERREFNO
,c.OP_NAME1 ,c.OP_NAME2 ,c.OP_NAME3 ,c.OP_ADDRESS1 ,c.OP_ADDRESS2 ,c.OP_ADDRESS3 ,c.ISSUER_CUSTOMERREFNO ,c.ISSUER_NAME1 ,c.ISSUER_NAME2 ,c.ISSUER_NAME3
,c.ISSUER_ADDRESS1 ,c.ISSUER_ADDRESS2 ,c.ISSUER_ADDRESS3 ,c.ISSUER_ACCOUNTNO ,c.BENEFICIARY_NAME_FLAG ,c.CP_NAME_FLAG ,c.OP_NAME_FLAG ,c.ISSUER_NAME_FLAG
,c.TRANSACTOR_NAME_FLAG ,c.SUSPICIOUS_ACTIVITY_CODE ,c.CPCUSTTYPE ,c.REGION ,c.TXN_DATE_TIME ,c.RUNID ,c.RUNDATE ,c.last_renewed_date ,c.account_opened_date

from
(
	SELECT *
	from ETL_AML_TRANSACTION
	where AccountNumber in
	(
		select AccountNumber from
		(
			select COUNT(TXNTYPE) as DTDPD#, AccountNumber
			from ETL_AML_TRANSACTION
			where TXNTYPE = 'dtdpd' and TXNSUBTYPE = 'PMT'
			group by AccountNumber, TXNDATE 
			having COUNT(TXNTYPE) = 2
		) a --where AccountNumber = '001121026559'
	) and TXNTYPE = 'DTDYK' --and AccountNumber = '001121026559'
) a
inner join ETL_AML_TRANSACTION b on b.AccountNumber = a.AccountNumber  and b.TXNAMOUNT = a.TXNAMOUNT and b.TXNTYPE <> a.TXNTYPE
inner join ETL_AML_TRANSACTION c on c.AccountNumber = a.AccountNumber and c.TXNAMOUNT = b.TXNAMOUNT and b.TXNTYPE = c.TXNTYPE and c.TXNREFNO <> b.TXNREFNO
where c.TXNAMOUNT > 500000 ) a where rn = 1

/************************************************/
/*** END - ADDITIONAL PLACEMENT (SAME AMOUNT) ***/
/************************************************/


UNION


/*********************************************/
/*** FTR - ADDITIONAL PLACEMENT (ROLLOVER) ***/
/*********************************************/

-- REVISED @ 10-20-2023

select 
a.*
--a.TXNDATE,a.TXNREFNO, a.TXNTYPE, a.TXNAMOUNT,a.last_renewed_date, b.txndate as AMLTXN_TXNDATE, b.TXNAMOUNT as AMLTXN_TXNAMOUNT
from (
    select
    --a.AccountNumber, 
    --a.TXNREFNO as A_TXNREFNO, a.TXNTYPE as A_TXNTYPE, a.TXNAMOUNT as A_TXNAMOUNT, a.INOUT as A_INOUT, a.last_renewed_date as LRD1,
    --b.TXNREFNO as B_TXNREFNO, B.TXNTYPE as B_TXNTYPE, B.TXNAMOUNT as B_TXNAMOUNT, B.INOUT as B_INOUT,b.last_renewed_date as LRD2,
    --c.TXNREFNO as C_TXNREFNO, c.TXNTYPE as C_TXNTYPE, c.TXNAMOUNT as C_TXNAMOUNT, B.INOUT as C_INOUT, c.last_renewed_date as LRD3

 

    c.TXNDATE ,a.TXNREFNO ,c.TXNTYPE ,c.TXNSUBTYPE ,c.TXNMODE ,c.TXNAMOUNT + b.TXNAMOUNT as TXNAMOUNT ,c.INOUT ,c.BRANCHCODE ,c.CURRENCY ,c.EXCHANGERATE
    ,c.PURPOSE ,c.CPNAME1 ,c.IMPORTED_DATE ,c.CPNAME2 ,c.CPNAME3 ,c.CPINSTITUTION ,c.CPINSTITUTIONCOUNTRY ,c.CPADDRESS1 ,c.CPADDRESS2 ,c.CPADDRESS3
    ,c.CORRESPONDENTBANK ,c.CORRESBANKCOUNTRYCODE ,c.CORRESBANKADDRESS1 ,c.CORRESBANKADDRESS2 ,c.CORRESBANKADDRESS3 ,c.INTERMEDIATORYINST ,c.INTERMEDIATORYINSTCOUNTRY
    ,c.INTERMEDIATORYINSTADDRESS1 ,c.INTERMEDIATORYINSTADDRESS2 ,c.INTERMEDIATORYINSTADDRESS3 ,c.PRODUCTTYPE ,c.PRODUCTOWNERNAME1 ,c.PRODUCTOWNERNAME2 
    ,c.PRODUCTOWNERNAME3 ,c.PRODUCTOWNERADDRESS1 ,c.PRODUCTOWNERADDRESS2 ,c.PRODUCTOWNERADDRESS3 ,c.INCEPTIONDATE ,c.MATUITYDATE ,c.NARRATION ,c.TXNNATURE
    ,c.FUNDSSOURCE ,c.FXAMOUNT ,c.POSTINGGROUPID ,c.POSTINGSEQNO ,c.SOURCE ,c.INPUTDATE ,c.CERTIFIEDDOCUMENTS ,c.REGULARDOCUMENTS ,c.TXNFORBRANCH ,c.BSRCODE
    ,c.DEBIT_CREDIT ,c.BENEFICIARYNAME1 ,c.BENEFICIARYNAME2 ,c.BENEFICIARYNAME3 ,c.BENEFICIARYADDRESS1 ,c.BENEFICIARYADDRESS2 ,c.BENEFICIARYADDRESS3 ,c.ACCOUNTID
    ,c.REMARKS ,c.OPBRANCHNAME ,c.OPACCOUNTNO ,c.DEALNO ,c.SRCTXNTYPE ,c.OTHERACCOUNT ,c.BENEFICIARY_TINNO ,c.BENEFICIARYCOUNTRY ,c.REASONCODE ,c.FIRST_IMPORTED_DATE
    ,c.SRC_TXN_REFNO ,c.cpaccountno ,c.EXPORTED_DATE ,c.ETL_FLAG ,c.pop_benificiaryaddress ,c.pop_benificiaryBOD ,c.OTHERACCOUNTNO ,c.SBCRefNoDetail
    ,c.OTHERACCOUNTBRANCH ,c.pop_benificiary ,c.SBCREFNO ,c.PO_GROUPID ,c.SRC_TXNTYPE ,c.customerno ,c.CardNumber ,c.AccountNumber ,c.STOCKREFNO ,c.AMOUNTOFCLAIM
    ,c.NOOFSHARES ,c.NETASSETVALUE ,c.BENEFICIARY_CUSTOMERREFNO ,c.BENEFICIARY_ACCOUNTNO ,c.BENEFICIARY_DATEOFBIRTH ,c.BENEFICIARY_PLACEOFBIRTH ,c.BENEFICIARY_IDType
    ,c.BENEFICIARY_IDNo ,c.BENEFICIARY_TelNo ,c.BENEFICIARY_NatureofBusiness ,c.SUSPICION_CUSTOMERREFNO ,c.SUSPICION_NAME1 ,c.SUSPICION_NAME2 ,c.SUSPICION_NAME3 
    ,c.SUSPICION_ADDRESS1 ,c.SUSPICION_ADDRESS2 ,c.SUSPICION_ADDRESS3 ,c.SUSPICION_ACCOUNTNO ,c.SUSPICION_DATEOFBIRTH ,c.SUSPICION_PLACEOFBIRTH ,c.SUSPICION_NATIONALITY
    ,c.SUSPICION_IDType ,c.SUSPICION_IDNo ,c.SUSPICION_TelNo ,c.SUSPICION_NatureofBusiness ,c.TRANSACTOR_CUSTOMERREFNO ,c.TRANSACTOR_NAME1 ,c.TRANSACTOR_NAME2 
    ,c.TRANSACTOR_NAME3 ,c.TRANSACTOR_ADDRESS1 ,c.TRANSACTOR_ADDRESS2 ,c.TRANSACTOR_ADDRESS3 ,c.TRANSACTOR_ACCOUNTNO ,c.CPCUSTOMERREFNO ,c.OP_CUSTOMERREFNO
    ,c.OP_NAME1 ,c.OP_NAME2 ,c.OP_NAME3 ,c.OP_ADDRESS1 ,c.OP_ADDRESS2 ,c.OP_ADDRESS3 ,c.ISSUER_CUSTOMERREFNO ,c.ISSUER_NAME1 ,c.ISSUER_NAME2 ,c.ISSUER_NAME3
    ,c.ISSUER_ADDRESS1 ,c.ISSUER_ADDRESS2 ,c.ISSUER_ADDRESS3 ,c.ISSUER_ACCOUNTNO ,c.BENEFICIARY_NAME_FLAG ,c.CP_NAME_FLAG ,c.OP_NAME_FLAG ,c.ISSUER_NAME_FLAG
    ,c.TRANSACTOR_NAME_FLAG ,c.SUSPICIOUS_ACTIVITY_CODE ,c.CPCUSTTYPE ,c.REGION ,c.TXN_DATE_TIME ,c.RUNID ,c.RUNDATE ,c.last_renewed_date ,c.account_opened_date

 

    from
    (
        SELECT ROW_NUMBER() OVER (PARTITION BY ACCOUNTNUMBER, TXNDATE, TXNSUBTYPE ORDER BY ACCOUNTNUMBER desc, TXNAMOUNT desc) RN, *
        from ETL_AML_TRANSACTION
        where AccountNumber in
        (
            select AccountNumber from 
            (
                select COUNT(TXNTYPE) as DTDPD#, AccountNumber
                from ETL_AML_TRANSACTION
                where TXNTYPE = 'dtdpd' and TXNSUBTYPE = 'PMT'
                group by AccountNumber, TXNDATE 
                having COUNT(TXNTYPE) = 2
            ) a
        ) and TXNTYPE = 'DTDYK'
    ) a
    inner join ETL_AML_TRANSACTION b on b.AccountNumber = a.AccountNumber  and b.TXNAMOUNT = a.TXNAMOUNT and b.TXNTYPE <> a.TXNTYPE
    inner join ETL_AML_TRANSACTION c on c.AccountNumber = a.AccountNumber and c.TXNAMOUNT <> a.TXNAMOUNT 
    where c.TXNAMOUNT <= 500000 and a.TXNAMOUNT > 500000 ) a
left join 
(
	select * from 
	(
		select ROW_NUMBER() over (partition by accountnumber order by txndate desc) rn,* from AML_TRANSACTION
		where AccountNumber not in 
		(
			select AccountNumber from 
			(
				select AccountNumber,count(TXNAMOUNT) as Flag1 from AML_TRANSACTION
				GROUP BY AccountNumber, TXNAMOUNT
				HAVING TXNAMOUNT > 500000
			) x 
		)
	) a
	where rn = 1 and TXNTYPE like '%td%'
)b on b.AccountNumber = a.AccountNumber
where b.TXNAMOUNT <= 500000 and b.TXNTYPE like '%td%' 

/***************************************************/
/*** END - FTR - ADDITIONAL PLACEMENT (ROLLOVER) ***/
/***************************************************/


UNION


/***************************************/
/*** WITHDRAWAL FILTERING PROCESS (A)***/
/***************************************/
-- FOR WITHDRAW ABOVE 500K 

select  
--a.AccountNumber, 
--a.TXNREFNO as A_TXNREFNO, a.TXNTYPE as A_TXNTYPE, a.TXNAMOUNT as A_TXNAMOUNT, a.INOUT as A_INOUT,
--b.TXNREFNO as B_TXNREFNO, B.TXNTYPE as B_TXNTYPE, B.TXNAMOUNT as B_TXNAMOUNT, B.INOUT as B_INOUT,
--c.TXNREFNO as C_TXNREFNO, c.TXNTYPE as C_TXNTYPE, c.TXNAMOUNT as C_TXNAMOUNT, B.INOUT as C_INOUT 
c.*
from
(
	select *
	from ETL_AML_TRANSACTION
	where AccountNumber in 
	(
	select AccountNumber from
		(
			select COUNT(TXNTYPE) as DTDYK#, AccountNumber
			from ETL_AML_TRANSACTION
			where TXNTYPE = 'DTDYK' and TXNSUBTYPE = 'PMT'
			group by AccountNumber, TXNDATE 
			having COUNT(TXNTYPE) = 2
		) a
	) and TXNTYPE = 'DTDPD'
) a
inner join ETL_AML_TRANSACTION b on b.AccountNumber = a.AccountNumber and b.TXNAMOUNT = a.TXNAMOUNT and b.TXNTYPE <> a.TXNTYPE
inner join ETL_AML_TRANSACTION c on c.AccountNumber = a.AccountNumber and c.TXNAMOUNT <> a.TXNAMOUNT 
where c.TXNAMOUNT > 500000


-- a. b. is the balance
-- c. is the withrawal


/*********************************************/
/*** END - WITHDRAWAL FILTERING PROCESS (A)***/
/*********************************************/
 

 UNION


/***************************************/
/*** WITHDRAWAL FILTERING PROCESS (B)***/
/***************************************/
-- BALANCE >500k

select 
--a.AccountNumber, 
--a.TXNREFNO as A_TXNREFNO, a.TXNTYPE as A_TXNTYPE, a.TXNAMOUNT as A_TXNAMOUNT, a.INOUT as A_INOUT,
--b.TXNREFNO as B_TXNREFNO, B.TXNTYPE as B_TXNTYPE, B.TXNAMOUNT as B_TXNAMOUNT, B.INOUT as B_INOUT,
--c.TXNREFNO as C_TXNREFNO, c.TXNTYPE as C_TXNTYPE, c.TXNAMOUNT as C_TXNAMOUNT, B.INOUT as C_INOUT 

a.*

from
(
	select *
	from ETL_AML_TRANSACTION
	where AccountNumber in 
	(
	select AccountNumber from
		(
			select COUNT(TXNTYPE) as DTDYK#, AccountNumber
			from ETL_AML_TRANSACTION
			where TXNTYPE = 'DTDYK' and TXNSUBTYPE = 'PMT'
			group by AccountNumber, TXNDATE 
			having COUNT(TXNTYPE) = 2
		) a
	) and TXNTYPE = 'DTDPD'
) a
inner join ETL_AML_TRANSACTION b on b.AccountNumber = a.AccountNumber and b.TXNAMOUNT = a.TXNAMOUNT and b.TXNTYPE <> a.TXNTYPE
inner join ETL_AML_TRANSACTION c on c.AccountNumber = a.AccountNumber and c.TXNAMOUNT <> a.TXNAMOUNT 
where c.TXNAMOUNT > 500000 and a.TXNAMOUNT > 500000



-- a. b. is the balance
-- c. is the withrawal

/*********************************************/
/*** END - WITHDRAWAL FILTERING PROCESS (B)***/
/*********************************************/



UNION



/*******************************/
/*** WITHDRAWAL SAME AMOUNTS ***/
/*******************************/


select
 TXNDATE , TXNREFNO , TXNTYPE , TXNSUBTYPE , TXNMODE , TXNAMOUNT, INOUT , BRANCHCODE , CURRENCY , EXCHANGERATE
, PURPOSE , CPNAME1 , IMPORTED_DATE , CPNAME2 , CPNAME3 , CPINSTITUTION , CPINSTITUTIONCOUNTRY , CPADDRESS1 , CPADDRESS2 , CPADDRESS3
, CORRESPONDENTBANK , CORRESBANKCOUNTRYCODE , CORRESBANKADDRESS1 , CORRESBANKADDRESS2 , CORRESBANKADDRESS3 , INTERMEDIATORYINST , INTERMEDIATORYINSTCOUNTRY
, INTERMEDIATORYINSTADDRESS1 , INTERMEDIATORYINSTADDRESS2 , INTERMEDIATORYINSTADDRESS3 , PRODUCTTYPE , PRODUCTOWNERNAME1 , PRODUCTOWNERNAME2 
, PRODUCTOWNERNAME3 , PRODUCTOWNERADDRESS1 , PRODUCTOWNERADDRESS2 , PRODUCTOWNERADDRESS3 , INCEPTIONDATE , MATUITYDATE , NARRATION , TXNNATURE
, FUNDSSOURCE , FXAMOUNT , POSTINGGROUPID , POSTINGSEQNO , SOURCE , INPUTDATE , CERTIFIEDDOCUMENTS , REGULARDOCUMENTS , TXNFORBRANCH , BSRCODE
, DEBIT_CREDIT , BENEFICIARYNAME1 , BENEFICIARYNAME2 , BENEFICIARYNAME3 , BENEFICIARYADDRESS1 , BENEFICIARYADDRESS2 , BENEFICIARYADDRESS3 , ACCOUNTID
, REMARKS , OPBRANCHNAME , OPACCOUNTNO , DEALNO , SRCTXNTYPE , OTHERACCOUNT , BENEFICIARY_TINNO , BENEFICIARYCOUNTRY , REASONCODE , FIRST_IMPORTED_DATE
, SRC_TXN_REFNO , cpaccountno , EXPORTED_DATE , ETL_FLAG , pop_benificiaryaddress , pop_benificiaryBOD , OTHERACCOUNTNO , SBCRefNoDetail
, OTHERACCOUNTBRANCH , pop_benificiary , SBCREFNO , PO_GROUPID , SRC_TXNTYPE , customerno , CardNumber , AccountNumber , STOCKREFNO , AMOUNTOFCLAIM
, NOOFSHARES , NETASSETVALUE , BENEFICIARY_CUSTOMERREFNO , BENEFICIARY_ACCOUNTNO , BENEFICIARY_DATEOFBIRTH , BENEFICIARY_PLACEOFBIRTH , BENEFICIARY_IDType
, BENEFICIARY_IDNo , BENEFICIARY_TelNo , BENEFICIARY_NatureofBusiness , SUSPICION_CUSTOMERREFNO , SUSPICION_NAME1 , SUSPICION_NAME2 , SUSPICION_NAME3 
, SUSPICION_ADDRESS1 , SUSPICION_ADDRESS2 , SUSPICION_ADDRESS3 , SUSPICION_ACCOUNTNO , SUSPICION_DATEOFBIRTH , SUSPICION_PLACEOFBIRTH , SUSPICION_NATIONALITY
, SUSPICION_IDType , SUSPICION_IDNo , SUSPICION_TelNo , SUSPICION_NatureofBusiness , TRANSACTOR_CUSTOMERREFNO , TRANSACTOR_NAME1 , TRANSACTOR_NAME2 
, TRANSACTOR_NAME3 , TRANSACTOR_ADDRESS1 , TRANSACTOR_ADDRESS2 , TRANSACTOR_ADDRESS3 , TRANSACTOR_ACCOUNTNO , CPCUSTOMERREFNO , OP_CUSTOMERREFNO
, OP_NAME1 , OP_NAME2 , OP_NAME3 , OP_ADDRESS1 , OP_ADDRESS2 , OP_ADDRESS3 , ISSUER_CUSTOMERREFNO , ISSUER_NAME1 , ISSUER_NAME2 , ISSUER_NAME3
, ISSUER_ADDRESS1 , ISSUER_ADDRESS2 , ISSUER_ADDRESS3 , ISSUER_ACCOUNTNO , BENEFICIARY_NAME_FLAG , CP_NAME_FLAG , OP_NAME_FLAG , ISSUER_NAME_FLAG
, TRANSACTOR_NAME_FLAG , SUSPICIOUS_ACTIVITY_CODE , CPCUSTTYPE , REGION , TXN_DATE_TIME , RUNID , RUNDATE , last_renewed_date , account_opened_date
from (
select   
ROW_NUMBER() over (partition by  c.accountnumber,  c.txnamount order by  c.accountnumber) as rn,
--a.AccountNumber, 
--a.TXNREFNO as A_TXNREFNO, a.TXNTYPE as A_TXNTYPE, a.TXNAMOUNT as A_TXNAMOUNT, a.INOUT as A_INOUT,
--b.TXNREFNO as B_TXNREFNO, B.TXNTYPE as B_TXNTYPE, B.TXNAMOUNT as B_TXNAMOUNT, B.INOUT as B_INOUT,
-- TXNREFNO as C_TXNREFNO,  TXNTYPE as C_TXNTYPE,  TXNAMOUNT as C_TXNAMOUNT, B.INOUT as C_INOUT 
 c.*
--a.*
from
(
	select *
	from ETL_AML_TRANSACTION
	where AccountNumber in 
	(
	select AccountNumber from
		(
			select COUNT(TXNTYPE) as DTDYK#, AccountNumber
			from ETL_AML_TRANSACTION
			where TXNTYPE = 'DTDYK' and TXNSUBTYPE = 'PMT'
			group by AccountNumber, TXNDATE 
			having COUNT(TXNTYPE) = 2
		) a
	) and TXNTYPE = 'DTDPD'
) a	
inner join ETL_AML_TRANSACTION b on b.AccountNumber = a.AccountNumber and b.TXNAMOUNT = a.TXNAMOUNT and b.TXNTYPE <> a.TXNTYPE -- and a.TXNREFNO <> b.TXNREFNO
inner join ETL_AML_TRANSACTION c on  c.AccountNumber = b.AccountNumber and  c.TXNAMOUNT = b.TXNAMOUNT and  c.TXNTYPE = b.TXNTYPE and  c.TXNREFNO <> b.TXNREFNO
where  c.TXNAMOUNT > 500000
) a
where rn = 1

/*************************************/
/*** END - WITHDRAWAL SAME AMOUNTS ***/
/*************************************/

UNION

--------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------- NON TD TRANSACTIONS -------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------


	select 
	 a.*
	from ETL_AML_TRANSACTION a
	left join aml_account b on a.AccountNumber = b.ACCOUNTNUMBER 
	where txntype = 'cpmd' and b.ACCOUNTTYPE not in ('901','902','903','904','906','907','908','909','911','912','913','914')

UNION


----------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------

SELECT * FROM ETL_AML_TRANSACTION WHERE TXNSUBTYPE = 'FTC'

UNION

SELECT * FROM ETL_AML_TRANSACTION WHERE PRODUCTTYPE = 'FTRQ' --transformed from other SP when already in AML_TRANSACTION

UNION 

select * from ETL_AML_TRANSACTION where txntype not like '%td%'and txntype not like '%cpmd%' and txntype not like '%LLPRD%'

UNION

select * from ETL_AML_TRANSACTION where source like '%ropa%'
------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------




UNION

select 
 [TXNDATE]      ,[TXNREFNO]      ,'CCOL' AS TXNTYPE      ,[TXNSUBTYPE]      ,[TXNMODE]      ,[TXNAMOUNT]      ,[INOUT]      ,a.[BRANCHCODE]      ,a.[CURRENCY]      ,[EXCHANGERATE]      ,[PURPOSE]      ,[CPNAME1]      ,a.[IMPORTED_DATE]      ,[CPNAME2]      ,[CPNAME3]      ,[CPINSTITUTION]      ,[CPINSTITUTIONCOUNTRY]      ,[CPADDRESS1]      ,[CPADDRESS2]      ,[CPADDRESS3]      ,[CORRESPONDENTBANK]      ,[CORRESBANKCOUNTRYCODE]      ,[CORRESBANKADDRESS1]      ,[CORRESBANKADDRESS2]      ,[CORRESBANKADDRESS3]      ,[INTERMEDIATORYINST]      ,[INTERMEDIATORYINSTCOUNTRY]      ,[INTERMEDIATORYINSTADDRESS1]      ,[INTERMEDIATORYINSTADDRESS2]      ,[INTERMEDIATORYINSTADDRESS3]      ,[PRODUCTTYPE]      ,[PRODUCTOWNERNAME1]      ,[PRODUCTOWNERNAME2]      ,[PRODUCTOWNERNAME3]      ,[PRODUCTOWNERADDRESS1]      ,[PRODUCTOWNERADDRESS2]      ,[PRODUCTOWNERADDRESS3]      ,[INCEPTIONDATE]      ,[MATUITYDATE]      ,[NARRATION]      ,[TXNNATURE]      ,[FUNDSSOURCE]      ,[FXAMOUNT]      ,[POSTINGGROUPID]      ,[POSTINGSEQNO]      ,a.[SOURCE]      ,[INPUTDATE]      ,[CERTIFIEDDOCUMENTS]      ,[REGULARDOCUMENTS]      ,[TXNFORBRANCH]      ,[BSRCODE]      ,[DEBIT_CREDIT]      ,[BENEFICIARYNAME1]      ,[BENEFICIARYNAME2]      ,[BENEFICIARYNAME3]      ,[BENEFICIARYADDRESS1]      ,[BENEFICIARYADDRESS2]      ,[BENEFICIARYADDRESS3]      ,a.[ACCOUNTID]      ,[REMARKS]      ,[OPBRANCHNAME]      ,[OPACCOUNTNO]      ,[DEALNO]      ,[SRCTXNTYPE]      ,[OTHERACCOUNT]      ,[BENEFICIARY_TINNO]      ,[BENEFICIARYCOUNTRY]      ,[REASONCODE]      ,a.[FIRST_IMPORTED_DATE]      ,[SRC_TXN_REFNO]      ,[cpaccountno]      ,a.[EXPORTED_DATE]      ,a.[ETL_FLAG]      ,[pop_benificiaryaddress]      ,[pop_benificiaryBOD]      ,[OTHERACCOUNTNO]      ,[SBCRefNoDetail]      ,[OTHERACCOUNTBRANCH]      ,[pop_benificiary]      ,[SBCREFNO]      ,[PO_GROUPID]      ,[SRC_TXNTYPE]      ,[customerno]      ,[CardNumber]      ,a.[AccountNumber]      ,[STOCKREFNO]      ,[AMOUNTOFCLAIM]      ,[NOOFSHARES]      ,[NETASSETVALUE]      ,[BENEFICIARY_CUSTOMERREFNO]      ,[BENEFICIARY_ACCOUNTNO]      ,[BENEFICIARY_DATEOFBIRTH]      ,[BENEFICIARY_PLACEOFBIRTH]      ,[BENEFICIARY_IDType]      ,[BENEFICIARY_IDNo]      ,[BENEFICIARY_TelNo]     ,[BENEFICIARY_NatureofBusiness]      ,[SUSPICION_CUSTOMERREFNO]      ,[SUSPICION_NAME1]      ,[SUSPICION_NAME2]      ,[SUSPICION_NAME3]      ,[SUSPICION_ADDRESS1]      ,[SUSPICION_ADDRESS2]      ,[SUSPICION_ADDRESS3]      ,[SUSPICION_ACCOUNTNO]      ,[SUSPICION_DATEOFBIRTH]      ,[SUSPICION_PLACEOFBIRTH]      ,[SUSPICION_NATIONALITY]      ,[SUSPICION_IDType]      ,[SUSPICION_IDNo]     ,[SUSPICION_TelNo]      ,[SUSPICION_NatureofBusiness]      ,[TRANSACTOR_CUSTOMERREFNO]      ,[TRANSACTOR_NAME1]      ,[TRANSACTOR_NAME2]      ,[TRANSACTOR_NAME3]      ,[TRANSACTOR_ADDRESS1]      ,[TRANSACTOR_ADDRESS2]      ,[TRANSACTOR_ADDRESS3]      ,[TRANSACTOR_ACCOUNTNO]      ,[CPCUSTOMERREFNO]      ,[OP_CUSTOMERREFNO]      ,[OP_NAME1]      ,[OP_NAME2]      ,[OP_NAME3]      ,[OP_ADDRESS1]      ,[OP_ADDRESS2]      ,[OP_ADDRESS3]      ,[ISSUER_CUSTOMERREFNO]      ,[ISSUER_NAME1]      ,[ISSUER_NAME2]      ,[ISSUER_NAME3]      ,[ISSUER_ADDRESS1]      ,[ISSUER_ADDRESS2]      ,[ISSUER_ADDRESS3]      ,[ISSUER_ACCOUNTNO]      ,[BENEFICIARY_NAME_FLAG]      ,[CP_NAME_FLAG]      ,[OP_NAME_FLAG]      ,[ISSUER_NAME_FLAG]      ,[TRANSACTOR_NAME_FLAG]      ,[SUSPICIOUS_ACTIVITY_CODE]      ,[CPCUSTTYPE]      ,[REGION]      ,[TXN_DATE_TIME]      ,a.[RUNID]   ,a.[RUNDATE],LAST_RENEWED_DATE,ACCOUNT_OPENED_dATE
from ETL_AML_TRANSACTION a
left join aml_account b on a.AccountNumber = b.ACCOUNTNUMBER 
where txntype in ('BPCHC') AND TXNSUBTYPE in ('CHD') AND CONVERT(FLOAT,TXNAMOUNT) > 500000

 


) A
INNER JOIN (select accountid, accountnumber, source, ACCOUNTTYPE,Row_Number() over (partition by accountnumber, source order by accountid DESC) RID from aml_account) B
	    on A.ACCOUNTNUMBER = B.ACCOUNTNUMBER and B.RID = 1	
	AND CASE WHEN A.SOURCE IN ('TRUST-UITF-UIN', 'TRUST-UITF-URE') THEN 'TRUST-UITF' 
			 WHEN A.SOURCE = 'REM-DEPO' THEN 'CASA'
			 WHEN A.SOURCE = 'ROPA_TXN' THEN 'ROPA_ACCOUNT' 
			 ELSE A.SOURCE END = B.SOURCE
LEFT JOIN (SELECT TXNID, TXNREFNO, TXNDATE FROM AML_TRANSACTION) C ON A.TXNREFNO = C.TXNREFNO AND CONVERT(DATE, A.TXNDATE) = CONVERT(DATE, C.TXNDATE)
WHERE C.TXNID IS NULL AND A.TXNTYPE IN (SELECT TRAN_CODE FROM AML_TRANSACTION_TYPE)




end

